print('Hello, let us find the sum of two numbers')
print('Please input the first number')
number1=input()
print('Please input the second number')
number2=input()
print('The sum of the two numbers is ' + str(int(number1)+int(number2)))
